apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-service-secret
type: Opaque
data:
  RabbitMQSettings__Username: bmFtYmF5YQ==
  RabbitMQSettings__Password: TmFtYmF5YUAyMDIx
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: rabbitmq
    template:
        metadata:
            labels:
                app: rabbitmq
        spec:
            containers:
            - name: rabbitmq
              image: scr.syseleven.de/nambaya-stack-qtlife/nambayadock_rabbitmq:v3
              ports:
                - containerPort: 5672
                - containerPort: 15672
                - containerPort: 15671
              env:
                - name: RABBITMQ_DEFAULT_USER
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-service-secret
                      key: RabbitMQSettings__Username
                - name: RABBITMQ_DEFAULT_PASS
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-service-secret
                      key: RabbitMQSettings__Password
              volumeMounts:
                - mountPath: /var/lib/rabbitmq
                  name: rabbitmq-claim0
                  subPath: rabbitmq
            volumes:
              - name: rabbitmq-claim0
                persistentVolumeClaim:
                   claimName: qtlife-pvc
            imagePullSecrets:
                - name: syseleven-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
spec:
    selector:
        app: rabbitmq
    ports:
      - name: "5672"
        port: 56072
        targetPort: 5672
      - name: "15672"
        port: 55673
        targetPort: 15672
    type: LoadBalancer