apiVersion: v1
kind: Secret
metadata:
  name: s3maintenance-service-secret
  namespace: nambaya-cardio
type: Opaque
data:
  FTPConfiguration__Password: QWdONjBmTzN5Nk5vSmlZUw==
  S3Configuration__SecretKey: MTYzNThlNDViMTA5NDkzM2E1NGI3ZTgzNjI2NWM1ZTU=
  S3Configuration__AccessKey: ZDE4MTI2ZGY4ZmE2NDY5MThjZjFmNDNlNDQ2NGZlYmY=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3maintenance-config
  namespace: nambaya-cardio
data:
  appsettings.json: |-
    {
      "DoBackup": true,
      "S3Configuration": {
        "AccessKey": "",
        "SecretKey": "",
        "EndPoint": "s3.cbk.cloud.syseleven.net",
        "BucketName": "nambaya-demo"
      },
      "FTPConfiguration": {
        "ServerUrl": "ftp://u251316.your-storagebox.de",
        "UserName": "u251316",
        "Password": ""
      },
      "RabbitMQSettings": {
        "Host": "rabbitmq",
        "VirtualHost": "/",
        "Quartz": "quartz",
        "Port": 56072,
        "ConnectionName": "S3Maintenance",
        "Username": "",
        "Password": ""
      },
      "Serilog": {
        "MinimumLevel": {
          "Default": "Debug",
          "Override": {
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information",
            "System": "Warning"
          }
        },
        "Using": [],
        "Properties": { "Application": "S3 Maintainance" },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} {Properties:j}{NewLine}{Exception}"
            }
          },
          {
            "Name": "RollingFile",
            "Args": {
              "pathFormat": "Logs/{Date}.log"
            }
          }
        ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: s3maintenance
    namespace: nambaya-cardio
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: s3maintenance
    template:
        metadata:
            labels:
                app: s3maintenance
        spec:
            containers:
            - name: s3maintenance
              image: scr.syseleven.de/nambaya-stack-cardio/s3maintenance:v19.6
              imagePullPolicy: "Always"
              securityContext:
                runAsUser: 0
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: RabbitMQSettings__Username
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-service-secret
                      key: RabbitMQSettings__Username
                - name: RabbitMQSettings__Password
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-service-secret
                      key: RabbitMQSettings__Password
                - name: S3Configuration__AccessKey
                  valueFrom:
                    secretKeyRef:
                      name: s3maintenance-service-secret
                      key: S3Configuration__AccessKey
                - name: S3Configuration__SecretKey
                  valueFrom:
                    secretKeyRef:
                      name: s3maintenance-service-secret
                      key: S3Configuration__SecretKey
                - name: FTPConfiguration__Password
                  valueFrom:
                    secretKeyRef:
                      name: s3maintenance-service-secret
                      key: FTPConfiguration__Password
              volumeMounts:
                - mountPath: /app/appsettings.json
                  name: config-volume
                  subPath: appsettings.json
                  readOnly: true
            volumes:
              - name: config-volume
                configMap:
                    name: s3maintenance-config
            imagePullSecrets:
              - name: syseleven-registry-secret
