apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: qtlife
type: Opaque
data:
  Serilog__WriteTo__1__Args__connectionString: c2VydmVyPW1zc3FsLXNlcnZpY2UsNzkwMTtEYXRhYmFzZT1RVF9Mb2dzO1VzZXIgSWQ9bmFtYmF5YWRiYWRtaW47UGFzc3dvcmQ9QUJDMTIzc3NpQDsgQXBwbGljYXRpb24gTmFtZT1Ob3RpZmljYXRpb24gQXBpOw==
  EmailSettings__EmailAddress: cXQtbGlmZS1zdXBwb3J0QG5hbWJheWEuY29t
  EmailSettings__EmailPassword: JHF0LWxpZmUtc3VwcG9ydCUwMzAy
  SmsSettings__Token: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUlzSW1wMGFTSTZJalZqTVRBNE56ZGlZelU1WVdKaFpHSmpOR1EzTldZMk5UazNNakpsTW1ZNU5XVmhZekUyWmpnd1ltSTRNV1l6WlRoallUUXdZelF4WlRWaU5XUm1OR1F5TjJZeU9XRm1aalUzWlRWaE5EUXhJbjAuZXlKaGRXUWlPaUl6SWl3aWFuUnBJam9pTldNeE1EZzNOMkpqTlRsaFltRmtZbU0wWkRjMVpqWTFPVGN5TW1VeVpqazFaV0ZqTVRabU9EQmlZamd4WmpObE9HTmhOREJqTkRGbE5XSTFaR1kwWkRJM1pqSTVZV1ptTlRkbE5XRTBOREVpTENKcFlYUWlPakUxT0RRME5qVXlOamdzSW01aVppSTZNVFU0TkRRMk5USTJPQ3dpWlhod0lqbzBOelF3TVRNNE9EWTRMQ0p6ZFdJaU9pSTJOREE1TlNJc0luTmpiM0JsY3lJNlcxMTkuaEVDejJ3c1FjVGF0aHo5bU9WVFNoQXhEN3k4MXdudnVpRnhXaTZCeHNPU014c3lWSHBEU2UxcnpYY1ZiSzE3SlVsN21tUkZOT2FJSWU5eExfRm9KR0E5eVdvTkhtVHUzRXJCZUdJNU9vSjVVaFNHanZhbTF6RWpLZUQtcGN5SVV1UE1Xak1GSFBfQklGZU16bW5mTWRsWlJIbFJQRnEwMUs0S0RqZ3MzakR2QmdNNWY4OUZTUlRQYVI2WUZLYU9Eb0dDRnVKQVZuR0ZGVUNhUGd4ZEFhRUhILWwxQlNEem5XZ3VaWEhuN1ZCaUs3cTZqQ1hQSFF4OWt3UFdKVFBIWWRMWWE4VHB2R1VaTVdrU084WGdMNjY1N3lkUFNHcHJ0Q1ppZ29xdUNyMS0waWJVYnVNaU1ZS3ZDdVJzRWVIbEp3Zk5Lc0sxNFhJQW56eDFxQk51UElTZkVKaDJiOENSczd0d3hlWXNjOWNQcE1CRUpVaVNQOVhVN3NRaHdRM0RnWTJYTkRVX3QzMzUzN2ZuQnhPOFBVN3VRc2xQcWdTVUJlRXRrWnplZGVtR3NjVDl3MnhVa2ZxeDBncnFvODlvc3R6YjZsUzNDYnphX1JSNUhPQUJfekpWNUNISWFDcHRHQzBhSlRNUVJCeDBDdkptZXlyT2dyR1lnM20xaXNZOGZkQkZMQ2V3cklkWmF1ZUpNQS1acUFNU2RzQVRvaG9pNkd6RmljVElRbVItZi1HN0UtSEpVSWd4b0xJelZxUkp3NnYzY0dRR3BWX3pmeG90NW1kVElFdktUOHE1bWR6ZGFhM1hHVTV0LU9wZndGdGhkSDNNZlJGZWlQcnRxOWdtbElXLTNLb2plams4TXphZlZQRmdnd29XOE5XWVlPZ0FiaERWTWVWeU1PTW8= 
  ApiSecretConfigurationSecret: QjNBOTRGNUEtOEVCNi00MkM0LUFDODctRUYxNjBGMEI1QjQw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: qtlife
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "EmailSettings": {
        "SmtpHost": "smtps.udag.de",
        "SmtpPort": "587",
        "EmailAddress": "",
        "EmailPassword": ""
      },
      "ApiSecretConfiguration": {
        "ApiName": "Notification API",
        "Secret": "",
        "Clientid": "notification_api_client",
        "Scope": "logging_api"
      },
      "WebServiceConfiguration": {
        "PharmacistServiceBaseUrl": "http://pharmacist:5002",
        "CardiologistServiceBaseUrl": "http://cardiologist:5004",
        "CentralGroupServiceBaseUrl": "http://centralgroup:5005",
        "NambayaUserServiceBaseUrl": "http://nambayauser:5007",
        "IdentityServerBaseUrl": "http://identity:5001",
        "PatientServiceBaseUrl": "http://patient:5001",
        "UserManagementServiceBaseUrl": "http://usermanagement:5003",
        "FileSharingServiceBaseUrl": "http://filesharing:5009",
        "LoggingServiceBaseUrl": "http://logging:5010",
        "PharmacistUIUrl": "https://qt-life.nambaya-medical.de/pharmacist",
        "CardiologistUIUrl": "https://qt-life.nambaya-medical.de/cardiologist",
        "CentralGroupUIUrl": "https://qt-life.nambaya-medical.de/center",
        "NambayaUserUIUrl": "https://qt-life.nambaya-medical.de/user"
      },
      "SmsSettings": {
        "ClientApiUri": "https://rest.spryngsms.com/v1/messages",
        "ContentType": "application/json",
        "Route": "business",
        "SentBy": "Nambaya",
        "Token": "",
        "Encoding": "auto"
      },
      "RabbitMQSettings": {
        "Host": "rabbitmq",
        "Username": "",
        "Password": "",
        "ConnectionName": "Notification API",
        "Port": 56072
      },
      "AllowedHosts": "*",
      "OverrideEmail": {
        "nikolaus.schumacher+pharma@nambaya.com": "nikolaus.schumacher@nambaya.com",
        "nikolaus.schumacher+cardio@nambaya.com": "nikolaus.schumacher@nambaya.com",
        "nikolaus.schumacher+center@nambaya.com": "nikolaus.schumacher@nambaya.com",
        "anna.fischer+pharma@nambaya.com": "anna.fischer@nambaya.com",
        "anna.fischer+cardio@nambaya.com": "anna.fischer@nambaya.com",
        "anna.fischer+center@nambaya.com": "anna.fischer@nambaya.com",
        "anna.fischer+user@nambaya.com": "anna.fischer@nambaya.com",
        "noah.herman+pharma@nambaya.com": "noah.herman@nambaya.com",
        "noah.herman+cardio@nambaya.com": "noah.herman@nambaya.com",
        "noah.herman+center@nambaya.com": "noah.herman@nambaya.com",
        "lutz.graumann+pharma@nambaya.com": "lutz.graumann@nambaya.com",
        "lutz.graumann+cardio@nambaya.com": "lutz.graumann@nambaya.com",
        "lutz.graumann+center@nambaya.com": "lutz.graumann@nambaya.com"
      },
      "Serilog": {
        "Using": [ "Serilog.Sinks.MSSqlServer" ],
        "Enrich": [ "FromLogContext" ],
        "Properties": { "Application": "Notification Api" },
        "MinimumLevel": "Information",
        "WriteTo": [
          {
            "Name": "Console"
          },
          {
            "Name": "MSSqlServer",
            "Args": {
              "connectionString": "",
              "sinkOptionsSection": {
                "tableName": "SeriLogs",
                "schemaName": "dbo",
                "autoCreateSqlTable": true,
                "batchPostingLimit": 1000,
                "period": "0.00:00:30"
              },
              "restrictedToMinimumLevel": "Information",
              "columnOptionsSection": {
                "disableTriggers": true,
                "clusteredColumnstoreIndex": false,
                "primaryKeyColumnName": "Id",
                "removeStandardColumns": [ "MessageTemplate", "Properties" ],
                "additionalColumns": [
                  {
                    "ColumnName": "ApplicationName",
                    "PropertyName": "Application",
                    "DataType": "varchar",
                    "DataLength": 50
                  },
                  {
                    "ColumnName": "CorrelationId",
                    "PropertyName": "CorrelationId",
                    "DataType": "varchar",
                    "DataLength": 50
                  }
                ]
              }
            }
          }
        ]
      }
    }
  appsettings.Development.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Trace",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: notification
    namespace: qtlife
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: notification
    template:
        metadata:
            labels:
                app: notification
        spec:
            containers:
            - name: notification
              image: scr.syseleven.de/nambaya-stack-qtlife/notification:v19.7
              imagePullPolicy: "Always"
              ports:
                - containerPort: 80
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: EmailSettings__EmailAddress
                  valueFrom:
                    secretKeyRef:
                      name: notification-service-secret
                      key: EmailSettings__EmailAddress
                - name: EmailSettings__EmailPassword
                  valueFrom:
                    secretKeyRef:
                      name: notification-service-secret
                      key: EmailSettings__EmailPassword
                - name: SmsSettings__Token
                  valueFrom:
                    secretKeyRef:
                      name: notification-service-secret
                      key: SmsSettings__Token
                - name: ApiSecretConfiguration__Secret
                  valueFrom:
                    secretKeyRef:
                      name: notification-service-secret
                      key: ApiSecretConfigurationSecret
                - name: RabbitMQSettings__Username
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-service-secret
                      key: RabbitMQSettings__Username
                - name: RabbitMQSettings__Password
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-service-secret
                      key: RabbitMQSettings__Password
                - name: Serilog__WriteTo__1__Args__connectionString
                  valueFrom:
                    secretKeyRef:
                      name: notification-service-secret
                      key: Serilog__WriteTo__1__Args__connectionString
              volumeMounts:
                - mountPath: /app/appsettings.json
                  name: config-volume
                  subPath: appsettings.json
                  readOnly: true
                - mountPath: /app/appsettings.Development.json
                  name: config-volume
                  subPath: appsettings.Development.json
                  readOnly: true
            volumes:
              - name: config-volume
                configMap:
                    name: notification-config
            imagePullSecrets:
                - name: syseleven-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: notification
    namespace: qtlife  
spec:
    selector:
        app: notification
    ports:
        - protocol: TCP
          port: 5014
          targetPort: 80