apiVersion: v1
kind: ConfigMap
metadata:
  name: identityserver4-admin-config
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "ConfigurationDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
        "PersistedGrantDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
        "IdentityDbConnection": "Server=mssql-service,7901;Database=Dev_Identity_UM;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
        "AdminLogDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
        "AdminAuditLogDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true"
      },
      "DatabaseProviderConfiguration": {
        "ProviderType": "SqlServer"
      },
      "AdminConfiguration": {
        "PageTitle": "QTLife IdentityServer4 Admin",
        "FaviconUri": "/favicon.ico",
        "IdentityAdminRedirectUri": "http://185.56.130.193:9000/signin-oidc",
        "IdentityServerBaseUrl": "http://185.56.130.193:50000",
        "IdentityAdminCookieName": "IdentityServerAdmin",
        "IdentityAdminCookieExpiresUtcHours": 12,
        "RequireHttpsMetadata": false,
        "TokenValidationClaimName": "name",
        "TokenValidationClaimRole": "role",
        "ClientId": "skoruba_identity_admin",
        "ClientSecret": "skoruba_admin_client_secret",
        "OidcResponseType": "code id_token",
        "Scopes": [
          "openid",
          "profile",
          "email",
          "roles"
        ],
        "AdministrationRole": "SkorubaIdentityAdminAdministrator"
      },
      "AuditLoggingConfiguration": {
        "Source": "IdentityServer.Admin.Web",
        "SubjectIdentifierClaim": "sub",
        "SubjectNameClaim": "name",
        "IncludeFormVariables": false
      },
      "CultureConfiguration": {
        "Cultures": [],
        "DefaultCulture": null
      }
    }

  appsettings.Development.json: |-
    {
      
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: identityserver4-admin
    namespace: default
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: identityserver4-admin
    template:
        metadata:
            labels:
                app: identityserver4-admin
        spec:
            containers:
            - name: identityserver4-admin
              image: scr.syseleven.de/nambaya-stack-qtlife/identityserver4-admin:v1
              imagePullPolicy: "Always"
              ports:
                - containerPort: 80
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Development
              volumeMounts:
                - mountPath: /app/appsettings.json
                  name: config-volume
                  subPath: appsettings.json
                  readOnly: true
                - mountPath: /app/appsettings.Development.json
                  name: config-volume
                  subPath: appsettings.Development.json
                  readOnly: true
            volumes:
              - name: config-volume
                configMap:
                    name: identityserver4-admin-config
            imagePullSecrets:
                - name: syseleven-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: identityserver4-admin
spec:
    selector:
        app: identityserver4-admin
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 80
    externalIPs:
        - 192.168.1.23