apiVersion: v1
kind: ConfigMap
metadata:
  name: identityserver4-sts-identity-config
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "ConfigurationDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
        "PersistedGrantDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
        "IdentityDbConnection": "Server=mssql-service,7901;Database=Dev_Identity_UM;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true"
      },
        "DatabaseProviderConfiguration": {
            "ProviderType": "SqlServer"
        },
        "CertificateConfiguration": {
            "UseTemporarySigningKeyForDevelopment": true,
            "CertificateStoreLocation": "LocalMachine",
            "CertificateValidOnly": true,
            "UseSigningCertificateThumbprint": false,
            "SigningCertificateThumbprint": "",
            "UseSigningCertificatePfxFile": false,
            "SigningCertificatePfxFilePath": "",
            "SigningCertificatePfxFilePassword": "",
            "UseValidationCertificatePfxFile": false,
            "ValidationCertificatePfxFilePath": "",
            "ValidationCertificatePfxFilePassword": "",
            "UseValidationCertificateThumbprint": false,
            "ValidationCertificateThumbprint": ""
        },
        "RegisterConfiguration": {
            "Enabled": true
        },
        "ExternalProvidersConfiguration": {
            "UseGitHubProvider": false,
            "GitHubClientId": "",
            "GitHubClientSecret": ""
        },
        "SmtpConfiguration": {
            "Host": "",
            "Login": "",
            "Password": ""
        },
        "SendgridConfiguration": {
            "ApiKey": "",
            "SourceEmail": "",
            "SourceName": ""
        },
        "LoginConfiguration": {
            "ResolutionPolicy": "Username"
        },
        "AdminConfiguration": {
            "PageTitle": "QTLife IdentityServer4",
            "HomePageLogoUri": "/images/skoruba-icon.png",
            "FaviconUri": "/favicon.ico",
            "IdentityAdminBaseUrl": "http://185.56.130.193:9000",
            "AdministrationRole": "SkorubaIdentityAdminAdministrator"
        },
      "CultureConfiguration": {
        "Cultures": [],
        "DefaultCulture": null
      }
    }

  appsettings.Development.json: |-
    {
      
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: identityserver4-sts-identity
    namespace: default
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: identityserver4-sts-identity
    template:
        metadata:
            labels:
                app: identityserver4-sts-identity
        spec:
            containers:
            - name: identityserver4-sts-identity
              image: scr.syseleven.de/nambaya-stack-qtlife/identityserver4-sts-identity:v1
              imagePullPolicy: "Always"
              ports:
                - containerPort: 80
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Development
              volumeMounts:
                - mountPath: /app/appsettings.json
                  name: config-volume
                  subPath: appsettings.json
                  readOnly: true
                - mountPath: /app/appsettings.Development.json
                  name: config-volume
                  subPath: appsettings.Development.json
                  readOnly: true
            volumes:
              - name: config-volume
                configMap:
                    name: identityserver4-sts-identity-config
            imagePullSecrets:
                - name: syseleven-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: identityserver4-sts-identity
spec:
    selector:
        app: identityserver4-sts-identity
    ports:
        - protocol: TCP
          port: 50000
          targetPort: 80
    externalIPs:
        - 192.168.1.23