apiVersion: v1
kind: ConfigMap
metadata:
  name: identityserver4-admin-api-config
data:
  appsettings.json: |-
    {
        "ConnectionStrings": {
            "ConfigurationDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
            "PersistedGrantDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
            "IdentityDbConnection": "Server=mssql-service,7901;Database=Dev_Identity_UM;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
            "AdminLogDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true",
            "AdminAuditLogDbConnection": "Server=mssql-service,7901;Database=Dev_Identity;User Id=sa;Password=ABC123ssi@;MultipleActiveResultSets=true"
        },
        "AdminApiConfiguration": {
            "ApiName": "Skoruba IdentityServer4 Admin Api",
            "ApiVersion": "v1",
            "ApiBaseUrl": "http://185.56.130.193:6000",
            "IdentityServerBaseUrl": "http://185.56.130.193:50000",
            "OidcSwaggerUIClientId": "skoruba_identity_admin_api_swaggerui",
            "OidcApiName": "skoruba_identity_admin_api",
            "AdministrationRole": "SkorubaIdentityAdminAdministrator",
            "RequireHttpsMetadata": false,
            "CorsAllowAnyOrigin": true,
            "CorsAllowOrigins": []
        },
        "DatabaseProviderConfiguration": {
            "ProviderType": "SqlServer"
        },
        "AuditLoggingConfiguration": {
            "Source": "IdentityServer.Admin.Api",
            "SubjectIdentifierClaim": "sub",
            "SubjectNameClaim": "name",
            "ClientIdClaim": "client_id"
        }
    }

  appsettings.Development.json: |-
    {
      
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: identityserver4-admin-api
    namespace: default
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: identityserver4-admin-api
    template:
        metadata:
            labels:
                app: identityserver4-admin-api
        spec:
            containers:
            - name: identityserver4-admin-api
              image: scr.syseleven.de/nambaya-stack-qtlife/identityserver4-admin-api:v1
              imagePullPolicy: "Always"
              ports:
                - containerPort: 80
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Development
              volumeMounts:
                - mountPath: /app/appsettings.json
                  name: config-volume
                  subPath: appsettings.json
                  readOnly: true
                - mountPath: /app/appsettings.Development.json
                  name: config-volume
                  subPath: appsettings.Development.json
                  readOnly: true
            volumes:
              - name: config-volume
                configMap:
                    name: identityserver4-admin-api-config
            imagePullSecrets:
                - name: syseleven-registry-secret
---
apiVersion: v1
kind: Service
metadata:
    name: identityserver4-admin-api
spec:
    selector:
        app: identityserver4-admin-api
    ports:
        - protocol: TCP
          port: 6000
          targetPort: 80
    externalIPs:
        - 192.168.1.23